(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-overwrite-define-key
   '("n" . next-line)
   '("p" . previous-line)
   '("<escape>" . ignore))
  (meow-leader-define-key
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))
  (meow-convert-define-key
   '("g" . meow-convert-exit)
   '("x" . scamx-X-keymap)
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("-" . negative-argument)
   '("n" . forward-paragraph)
   '("p" . backward-paragraph)
   '("f" . forward-word)
   '("b" . backward-word)
   '("d" . kill-word)
   '("D" . backward-kill-word)
   '("e" . forward-sentence)
   '("a" . backward-sentence)
   '("k" . kill-sentence)
   '("K" . backward-kill-sentence)
   '("h" . mark-paragraph)
   '("u" . undo)
   '("/" . undo-redo)
   '("y" . yank)   
   '("w" . kill-ring-save)
   ;; '("s" . suspend)   ; TODO: allow a command in the normal mode to be excuted in the convert mode without leaving the convert mode
   '("SPC" . set-mark-command))
  (meow-visit-define-key
   '("g" . meow-visit-exit-all)
   '("x" . scamx-X-keymap)
   '("l" . meow-last-buffer)
   '("n" . next-buffer)
   '("p" . previous-buffer)
   '("f" . other-window)
   '("b" . previous-window-any-frame)
   '("c" . clone-buffer)
   '("s" . scratch-buffer)
   '("d" . scroll-up-command)
   '("u" . scroll-down-command)
   '("e" . scroll-down-line)
   '("a" . scroll-up-line)
   '("r" . revert-buffer)
   '("0" . balance-windows)
   '("m" . minimize-window)
   '("M" . maximize-window)
   '("+" . bold-enlarge-window-horizontally)
   '("-" . bold-shrink-window-horizontally))
   ;; '("w" . ace-swap-window)		;
   ;; '("t" . ace-select-window))       ;
  (meow-normal-define-key
   '("x" . scamx-X-keymap)
   '("c" . meow-convert)
   '("v" . meow-visit-all)
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("!" . shell-command)
   '("$" . ispell-word)
   '("%" . query-replace)   
   '("-" . negative-argument)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . move-beginning-of-line)
   '("e" . move-end-of-line)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("g" . my/meow-escape)
   '("b" . backward-char)
   '("i" . meow-insert)
   '("o" . meow-open-below)
   '("O" . meow-open-above)
   '("n" . next-line)
   '("p" . previous-line)
   '("f" . forward-char)
   '("j" . newline)
   '("m" . back-to-indentation)
   '("s" . isearch-forward)
   ;; '("s" . swiper)
   '("w" . kill-ring-save)
   '("y" . yank)
   '("q" . meow-quit)
   '("Q" . goto-line)
   ;; '("Q" . consult-goto-line)
   '("k" . meow-kill)
   '("t" . meow-till)
   '("u" . undo)   
   '("/" . undo-redo)
   '("h" . meow-line)
   '("z" . zap-to-char)
   '("Z" . zap-up-to-char)   
   '("r" . repeat)
   '("l" . recenter-top-bottom)
   '("\\" . delete-horizontal-space)
   '("=" . mark-word)
   '("SPC" . set-mark-command)
   '("<escape>" . ignore)))

(use-package meow
  :config
  (meow-setup)
  (meow-global-mode 1)
  (setq meow-expand-hint-remove-delay 0))
